### ISSUE TITLE
ASE Manager Tracker - Corp

### ISSUE THREAD

**Issue by ZackConord** [ZackConord/ASE-Team#2]
# ASE CORP Tracker

| Project Name  | Status          | Estimated Completion | Notes                 | Links                          |
|---------------|-----------------|----------------------|-----------------------|--------------------------------|
| GHAzDO at Scale Issue     | Working | Q3 2024              | This issue captures the action items and priorities coming out of the monthly GHAzDO update with Julia. | [GitHub Issue](https://github.com/github/advanced-security-field/issues/5962)                |
| Corp discount requests H2     | Working | Q2 2024              | GHAS + Teams Promo   | [GitHub Issue](https://github.com/github/advanced-security-field/issues/5971)                  |
| 3rd Party Tools Guidance / Scale motion - Advanced Security Go-To-Market Program     | Working   | Q3 2024              | TBD  | [GitHub Issue](https://github.com/github/advanced-security-field/issues/5123)              |
| GHAS Lunch & Learn OAR     | Working     | Q4 2024              | @pladuke is DRI spinning up issue for this OAR and taking lead with SE partnership, 3/1 start date     | [GitHub Issue](#)           |
| FY24 H2 Promo Requests - Corporate| Working     | Q3 2024              | Request: GHAS Getting Started offer for GHAS SKU. Also, we would like approval to continue the Team + GHAS promo in H2.     | [GitHub Issue](https://github.com/github/advanced-security-field/issues/5971)           |
| Update MEDDPICC questions for GHAS POC request issue| Working     | Q3 2024              | Restructuring qualification criteria for GHAS POC's, @caseyhonan DRI     | [GitHub Issue](https://github.com/github/advanced-security-field/issues/4933)           |
| PQL Generation Campaign for CodeQl Autofix     | Completed       | Q2 2022              | Successfully launched| [GitHub Issue](https://github.com/github/advanced-security-field/issues/5538)                 |

# Important Links
Weekly Team ASE Meeting:
- Snippets for Jamie Jones: [Working Document](https://docs.google.com/document/d/1DIr53t1YRr1nww28lQLvHwFZDsFi4Xrd1yQNOHHD-Pc/edit#heading=h.cvvpiy3b8f8c)
- Agenda Planning Document: [Working Document](TBD)
---------------------------------------------------------
- GHAS ASE OKR's for H2: [Working Document](https://github.com/orgs/github/projects/4380/views/61)
- SMB Creative Discount Offers Doc: [Working Document](https://docs.google.com/document/d/16aZUNuThf8TuXctWBzBOSbRTQU2-gkYojcAnRDSnYYw/edit#heading=h.b01sfvtnduzu)

# Upcoming Events
RSA: 

- [ ] Connect the dots with Harry. 
- [ ] Work on coming up with Activities for SMB and who can attend RSA 

BlackHat: 
- [ ] Work on coming up with Activities for SMB and who can attend BlackHat 

# ASE Team Requests

| Request Name  | Status          | Estimated Completion | Notes                 | Links                          |
|---------------|-----------------|----------------------|-----------------------|--------------------------------|
| Advanced Security Customer Profile data from Looker query     | Working | Q3 2024              | TBD but this is very important | [GitHub Issue](https://github.com/github/cs-analytics/issues/2304)                |

# Enablement Sessions

| Topic                       | Guest Speaker | Proposed Date | Status     | Notes                 | Links                        |
|-----------------------------|-----------------|---------------|------------|-----------------------|------------------------------|
| CodeQl vs competitive SAST engines, Thread model in GHAS   | None      | Feb 2024    | Proposed   | TBD     | [Session Plan](#)            |
| Security Configurations in GHAS | @dorothymitchell  | Feb 14, 24'   | Scheduled| TBD | [TBD](#)          |
| DfC + Sentinel MSFT strategy | Harry Rossof @ MSFT  | Jan 24th, 24'   | Completed | Positive feedback from team, follow up with Harry scheduled | [Session Recording](#)          |
